In [117]:
# DSC 540
# Week 7 & 8
# Summer 2024
# Term Project Milestone 4
# Created By Matthew Heinen
# 7/20/24

# Weather and Carlos Santanaâ€™s Effectiveness
## DSC 540: Milestone 3

## Read in Ballpark data. 

Here we will read in the ballpark data from the CSV file that was saved in a previous step. In order to make the API call and record our weather data we will need the latitude and longitude from the ballpark dataset.

In [121]:
# Import packages 
import pandas as pd

In [123]:
# Use read_csv to read file into dataframe. 
ballpark = pd.read_csv('ballpark_data_web.csv')

In [125]:
# Preview ballpark dataframe. 
ballpark.head(10)

,Ballpark,City,Surface,Team,Roof type,Lat,Long,Alt
0,American Family Field,"Milwaukee, Wisconsin",Grass,Milwaukee Brewers,Retractable,43.03,-87.97,602
1,Angel Stadium,"Anaheim, California",Grass,Los Angeles Angels,Open,33.80,-117.88,154
2,Busch Stadium,"St. Louis, Missouri",Grass,St. Louis Cardinals,Open,38.62,-90.19,438
3,Chase Field,"Phoenix, Arizona",Artificial turf,Arizona Diamondbacks,Retractable,33.45,-112.07,1059
4,Citi Field,"Queens, New York",Grass,New York Mets,Open,40.76,-73.85,13
5,Citizens Bank Park,"Philadelphia, Pennsylvania",Grass,Philadelphia Phillies,Open,39.91,-75.17,19
6,Comerica Park,"Detroit, Michigan",Grass,Detroit Tigers,Open,42.34,-83.05,602
7,Coors Field,"Denver, Colorado",Grass,Colorado Rockies,Open,39.76,-104.99,5197
8,Dodger Stadium,"Los Angeles, California",Grass,Los Angeles Dodgers[nb 2],Open,34.07,-118.24,501
9,Fenway Park,"Boston, Massachusetts",Grass,Boston Red Sox[nb 3],Open,42.35,-71.10,16

## Read in Carlos Santana Balls in Play Data 

Here we will need to read in the carlos data from the CSV file saved in Milestone 2. In order to make the API call we will need the date and time information to pull weather data for the specific time.

In [128]:
# Use read_csv to read file into dataframe. 
carlos = pd.read_csv('carlos_balls_in_play.csv')

In [130]:
# Preview carlos dataframe. 
carlos.head(10)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,pitcher_name,pitcher_id,ab_result,pitch_zone_location,description,...,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,unix_time
0,SI,2018-06-19,101.2,-1.43,6.18,"Hicks, Jordan",663855,field_out,1,"Carlos Santana grounds out, shortstop Yairo Mu...",...,7,6,6,7,Standard,Standard,245.0,-0.086,-0.232,1529452800
1,FF,2015-05-24,100.9,0.84,6.34,"Chapman, Aroldis",547973,single,7,Carlos Santana singles on a ground ball to cen...,...,1,5,5,1,Standard,Standard,NaN,0.012,0.578,1432512000
2,SI,2019-05-26,100.5,0.86,6.66,"Alvarado, JosÃ©",621237,force_out,9,"Carlos Santana grounds into a force out, field...",...,6,3,3,6,Standard,Standard,143.0,-0.040,-0.459,1558915200
3,FF,2023-06-03,100.2,-1.47,6.24,"Hicks, Jordan",663855,single,2,Carlos Santana singles on a fly ball to left f...,...,1,4,4,1,Strategic,Standard,210.0,0.064,0.748,1685836800
4,FF,2019-09-14,100.1,-1.55,6.44,"Graterol, Brusdar",660813,field_out,12,"Carlos Santana grounds out, shortstop Jorge Po...",...,4,5,5,4,Infield shift,Standard,205.0,-0.018,-0.286,1568505600
5,FC,2022-04-11,100.1,-0.46,6.06,"Clase, Emmanuel",661403,field_out,5,"Guardians challenged (force play), call on the...",...,10,7,7,10,Infield shift,Standard,194.0,-0.012,-0.112,1649721600
6,FF,2018-06-25,100.0,0.51,6.14,"Chapman, Aroldis",547973,field_out,7,Carlos Santana flies out to left fielder Gianc...,...,4,1,1,4,Standard,Standard,156.0,-0.047,-0.447,1529971200
7,FF,2017-08-21,99.7,-2.03,5.91,"Kelly, Joe",523260,field_out,3,Carlos Santana flies out to center fielder Jac...,...,4,3,3,4,Standard,Standard,203.0,-0.061,-0.225,1503360000
8,FF,2019-07-18,99.7,-1.36,6.15,"Rosenthal, Trevor",572096,field_out,6,Carlos Santana flies out to right fielder Nich...,...,3,5,5,3,Infield shift,Standard,205.0,0.000,-0.219,1563494400
9,FF,2024-05-07,99.5,-0.49,6.65,"Stanek, Ryne",592773,field_out,2,Carlos Santana flies out to center fielder Jul...,...,6,6,6,6,Infield shade,Standard,199.0,-0.050,-0.266,1715126400

## Add ballpark latitude longitude to carlos DataFrame
Here we will add the latitude and longitude columns to the carlos DataFrame. This way we can pull our weather data.

In [133]:
# import packages 
import pandas as pd

In [135]:
# Read in team abreviation key using read_csv
ab_key = pd.read_csv('team name and abreviations.csv')

# preview key 
ab_key.head(10)

              team_name abreviation
0  Arizona Diamondbacks         ari
1        Atlanta Braves         atl
2     Baltimore Orioles         bal
3        Boston Red Sox         bos
4     Chicago White Sox         cws
5          Chicago Cubs         chc
6      Cinncinnati Reds         cin
7     Cleveland Indians         cle
8      Colorado Rockies         col
9        Detroit Tigers         det

In [137]:
# Transform the ab_key DataFrame to make the abreviations all upper case. 

ab_key['abreviation'] = ab_key['abreviation'].str.upper()

# Preview transformation. 

ab_key.head(10)

              team_name abreviation
0  Arizona Diamondbacks         ARI
1        Atlanta Braves         ATL
2     Baltimore Orioles         BAL
3        Boston Red Sox         BOS
4     Chicago White Sox         CWS
5          Chicago Cubs         CHC
6      Cinncinnati Reds         CIN
7     Cleveland Indians         CLE
8      Colorado Rockies         COL
9        Detroit Tigers         DET

In [139]:
# Use merge to perform left join to add the team_name to the carlos file.

carlos = pd.merge(carlos, ab_key, left_on='home_team', right_on='abreviation', how='left')

In [141]:
print(carlos.columns)

Index(['pitch_type', 'game_date', 'release_speed', 'release_pos_x',
       'release_pos_z', 'pitcher_name', 'pitcher_id', 'ab_result',
       'pitch_zone_location', 'description', 'game_type', 'batter_stance',
       'p_throws', 'home_team', 'away_team', 'hit_location', 'bb_type',
       'balls', 'strikes', 'pitch_hor_break', 'pitch_ver_break', 'plate_x',
       'plate_z', 'on_3b', 'on_2b', 'on_1b', 'outs_when_up', 'inning',
       'inning_topbot', 'hit_distance_sc', 'launch_speed', 'launch_angle',
       'effective_speed', 'release_spin_rate', 'release_extension', 'game_id',
       'release_pos_y', 'estimated_ba_using_speedangle',
       'estimated_woba_using_speedangle', 'babip_value', 'iso_value',
       'contact_type', 'at_bat_number', 'pitch_number', 'pitch_name',
       'home_score', 'away_score', 'bat_score', 'fld_score', 'post_away_score',
       'post_home_score', 'post_bat_score', 'post_fld_score',
       'if_fielding_alignment', 'of_fielding_alignment', 'spin_axis',
       'delta_home_win_exp', 'delta_run_exp', 'unix_time', 'team_name',
       'abreviation'],
      dtype='object')

In [143]:
# Use Merge on home_team in order to find the ballpark latitude and longitude. 

carlos_lo = pd.merge(carlos, ballpark, left_on='team_name', right_on='Team', how='left')

In [145]:
# Preview new dataframe with location data. 

carlos_lo.head(10)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,pitcher_name,pitcher_id,ab_result,pitch_zone_location,description,...,team_name,abreviation,Ballpark,City,Surface,Team,Roof type,Lat,Long,Alt
0,SI,2018-06-19,101.2,-1.43,6.18,"Hicks, Jordan",663855,field_out,1,"Carlos Santana grounds out, shortstop Yairo Mu...",...,Philadelphia Phillies,PHI,Citizens Bank Park,"Philadelphia, Pennsylvania",Grass,Philadelphia Phillies,Open,39.91,-75.17,19.0
1,FF,2015-05-24,100.9,0.84,6.34,"Chapman, Aroldis",547973,single,7,Carlos Santana singles on a ground ball to cen...,...,Cleveland Indians,CLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SI,2019-05-26,100.5,0.86,6.66,"Alvarado, JosÃ©",621237,force_out,9,"Carlos Santana grounds into a force out, field...",...,Cleveland Indians,CLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FF,2023-06-03,100.2,-1.47,6.24,"Hicks, Jordan",663855,single,2,Carlos Santana singles on a fly ball to left f...,...,Pittsburgh Pirates,PIT,PNC Park,"Pittsburgh, Pennsylvania",Grass,Pittsburgh Pirates,Open,40.45,-80.01,724.0
4,FF,2019-09-14,100.1,-1.55,6.44,"Graterol, Brusdar",660813,field_out,12,"Carlos Santana grounds out, shortstop Jorge Po...",...,Cleveland Indians,CLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,FC,2022-04-11,100.1,-0.46,6.06,"Clase, Emmanuel",661403,field_out,5,"Guardians challenged (force play), call on the...",...,Kansas City Royals,KC,Kauffman Stadium,"Kansas City, Missouri",Grass,Kansas City Royals,Open,39.05,-94.48,886.0
6,FF,2018-06-25,100.0,0.51,6.14,"Chapman, Aroldis",547973,field_out,7,Carlos Santana flies out to left fielder Gianc...,...,Philadelphia Phillies,PHI,Citizens Bank Park,"Philadelphia, Pennsylvania",Grass,Philadelphia Phillies,Open,39.91,-75.17,19.0
7,FF,2017-08-21,99.7,-2.03,5.91,"Kelly, Joe",523260,field_out,3,Carlos Santana flies out to center fielder Jac...,...,Cleveland Indians,CLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,FF,2019-07-18,99.7,-1.36,6.15,"Rosenthal, Trevor",572096,field_out,6,Carlos Santana flies out to right fielder Nich...,...,Cleveland Indians,CLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,FF,2024-05-07,99.5,-0.49,6.65,"Stanek, Ryne",592773,field_out,2,Carlos Santana flies out to center fielder Jul...,...,Minnesota Twins,MIN,Target Field,"Minneapolis, Minnesota",Grass,Minnesota Twins,Open,44.98,-93.28,840.0

In [22]:
import requests

# Replace 'YOUR_API_KEY' with your actual API key
api_key = '6b1915f8a711e908db855ea4824218f5'
base_url = 'https://history.openweathermap.org/data/2.5/history/city'

# Specify the parameters for the API call
params = {
    'lat': '43.03',  # Replace with the name of the city
    'lon': '-87.97',  # Replace with the start date in the format 'YYYY-MM-DD'
    'start': '1529452800',  # Replace with the end date in the format 'YYYY-MM-DD'
    'type': 'hour',
    'cnt': '1',  # Number of results to return
    'appid': api_key
}
call = base_url + '?lat=43.0300000&lon=-87.9700000&type=hour&start=1529452800&appiid=' +api_key
response = requests.get(call)


# Check if the request was successful
if response.status_code == 200:
    data = response.json()  # Convert the response to JSON format
    # Process the data as needed
else:
    print('Failed to retrieve data:', response.status_code)

Failed to retrieve data: 401

In [14]:
import requests
response = requests.get('https://api.openweathermap.org/data/2.5/weather?lat=43.03&lon=-87.97&appid=6b1915f8a711e908db855ea4824218f5')

response.json()

{'coord': {'lon': -87.97, 'lat': 43.03},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01d'}],
 'base': 'stations',
 'main': {'temp': 289.44,
  'feels_like': 289.29,
  'temp_min': 287.61,
  'temp_max': 290.22,
  'pressure': 1023,
  'humidity': 83,
  'sea_level': 1023,
  'grnd_level': 998},
 'visibility': 10000,
 'wind': {'speed': 1.54, 'deg': 300},
 'clouds': {'all': 0},
 'dt': 1721998394,
 'sys': {'type': 2,
  'id': 2081761,
  'country': 'US',
  'sunrise': 1721990214,
  'sunset': 1722043178},
 'timezone': -18000,
 'id': 5278580,
 'name': 'West Milwaukee',
 'cod': 200}

In [20]:
import openmeteo_requests

import requests_cache
import pandas as pd
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
	"latitude": 52.52,
	"longitude": 13.41,
	"start_date": "2004-07-10",
	"end_date": "2004-07-24",
	"hourly": "temperature_2m"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates {response.Latitude()}Â°N {response.Longitude()}Â°E")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
	end = pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}
hourly_data["temperature_2m"] = hourly_temperature_2m

hourly_dataframe = pd.DataFrame(data = hourly_data)
print(hourly_dataframe)

Coordinates 52.5483283996582Â°N 13.407821655273438Â°E
Elevation 38.0 m asl
Timezone None None
Timezone difference to GMT+0 0 s
                         date  temperature_2m
0   2004-07-10 00:00:00+00:00       15.688999
1   2004-07-10 01:00:00+00:00       15.139000
2   2004-07-10 02:00:00+00:00       14.539000
3   2004-07-10 03:00:00+00:00       13.839000
4   2004-07-10 04:00:00+00:00       13.389000
..                        ...             ...
355 2004-07-24 19:00:00+00:00       20.188999
356 2004-07-24 20:00:00+00:00       18.838999
357 2004-07-24 21:00:00+00:00       17.938999
358 2004-07-24 22:00:00+00:00       17.338999
359 2004-07-24 23:00:00+00:00       16.588999

[360 rows x 2 columns]

In [24]:
response = requests.get('https://history.openweathermap.org/data/2.5/history/city?lat=43.0300000&lon=-87.9700000&type=hour&start=1529452800&appid=6b1915f8a711e908db855ea4824218f5')
response.json()

{'code': 400000, 'message': 'requested data is out of allowed range'}